variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - sonarqube  # Add a new stage for SonarQube analysis
  - deploy

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test

sonarqube:
  stage: sonarqube
  script:
    - ./gradlew sonar
  allow_failure: true

deploy:
  stage: deploy
  script:
    - ./gradlew clean assemble
    - docker build -t housingsystem-backend .
    - docker stop housingSystem-backend-staging
    - docker rm housingSystem-backend-staging
    - docker run -d -p 8090:8080 --net=docker_housingSystem_network_staging --env spring_profiles_active=staging --name=housingSystem-backend-staging housingsystem-backend